version: '2'
services:
  rhasspy:
    image: synesthesiam/rhasspy-server:latest
    environment:
      - RHASSPY_PROFILES=/profiles
      - RHASSPY_TTS_DIR=/tts
    volumes:
      - ./rhasspy/profiles:/profiles
      - ./rhasspy/tts:/tts
    devices:
      - /dev/snd:/dev/snd
    ports:
      - "12101:12101"
  hass:
    image: homeassistant/home-assistant
    volumes:
      - ./home-assistant/config:/config
    ports:
      - "8123:8123"
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
