openapi: "3.0.0"
info:
  title: 'Rhasspy Voice Assistant'
  version: '2.4'
  description: 'API for Rhasspy Voice Assistant Toolkit'
schemes:
  - http
paths:
  /api/version:
    get:
      summary: 'Get Rhasspy version'
      produces:
        - text/plain
      responses:
        '200':
          description: OK
          schema:
            type: string
  /api/profiles:
    get:
      summary: 'Get available profiles'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
  /api/profile:
    get:
      summary: 'Get profile settings'
      produces:
        - application/json
      parameters:
        - in: query
          name: layers
          description: ''
          enum: [all, defaults, profile]
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
    post:
      summary: 'Overwrite profile settings'
      produces:
        - application/json
      requestBody:
        description: 'JSON to write to profile'
        required: true
        content:
          application/json:
            schema:
              type: object
      parameters:
        - in: query
          name: layers
          description: ''
          enum: [default, profile]
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
  /api/listen-for-wake:
    post:
      summary: 'Make Rhasspy listen for the wake word'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: string
  /api/listen-for-command:
    post:
      summary: 'Make Rhasspy listen for a command'
      produces:
        - application/json
      parameters:
        - in: query
          name: nohass
          description: 'True if intent should NOT be sent to Home Assistant'
          schema:
            type: boolean
            default: false
        - in: query
          name: entity
          description: 'Set slot named entity in recognized intent to value'
          schema:
            type: string
        - in: query
          name: value
          description: 'Set slot named entity in recognized intent to value'
          schema:
            type: string
        - in: query
          name: timeout
          description: 'Number of seconds before empty intent is returned'
          schema:
            type: float
      responses:
        '200':
          description: Intent
          schema:
            type: object
  /api/microphones:
    get:
      summary: 'Get list of available microphones'
      produces:
        - application/json
      responses:
        '200':
          description: Available microphone names, descriptions
          schema:
            type: object
  /api/test-microphones:
    get:
      summary: 'Get list of available microphones and if they are working'
      produces:
        - application/json
      responses:
        '200':
          description: Available microphone names, descriptions
          schema:
            type: object
  /api/speakers:
    get:
      summary: 'Get list of available speakers'
      produces:
        - application/json
      responses:
        '200':
          description: Available speakers names, descriptions
          schema:
            type: object
  /api/pronounce:
    post:
      summary: 'Pronounce a word or set of phonemes'
      produces:
        - text/plain
        - audio/wav
      requestBody:
        description: 'Word of phonemes to pronounce'
        required: true
        content:
          text/plain:
            schema:
              type: string
      parameters:
        - in: query
          name: pronounce_type
          description: 'Input type'
          required: true
          schema:
            type: string
            enum: [word, phonemes]
        - in: query
          name: download
          description: 'Return WAV file instead of using speakers'
          schema:
            type: boolean
            default: false
        - in: query
          name: voice
          description: 'Voice/language to use (defaults to profile language)'
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
            audio/wav:
              schema:
                type: string
                format: binary
  /api/lookup:
    post:
      summary: 'Look up a word in the dictionary or guess pronunciation'
      produces:
        - application/json
      requestBody:
        description: 'Word to look up'
        required: true
        content:
          text/plain:
            schema:
              type: string
      parameters:
        - in: query
          name: n
          description: 'Number of pronunciations to generate'
          schema:
            type: integer
            default: 5
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /api/phonemes:
    get:
      summary: 'Get examples of phonemes for a profile'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /api/sentences:
    get:
      summary: 'Get example sentences for profile'
      produces:
        - text/plain
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
    post:
      summary: 'Overwrite example sentences for profile'
      requestBody:
        description: 'Example sentences in ini/jsgf format'
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/custom-words:
    get:
      summary: 'Get custom words for profile'
      produces:
        - text/plain
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
    post:
      summary: 'Overwrite custom workds for profile'
      requestBody:
        description: 'Custom words as a CMU dictionary'
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/unknown-words:
    get:
      summary: 'Get unknown words for profile'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /api/train:
    post:
      summary: 'Re-train speech/intent recognizers for profile'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/restart:
    post:
      summary: 'Restart the Rhasspy server'
      parameters:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/speech-to-text:
    post:
      summary: 'Transcribe WAV data to text'
      requestBody:
        description: 'WAV data (16-bit 16Khz mono preferred)'
        required: true
        content:
          audio/wav:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/text-to-intent:
    post:
      summary: 'Extract intent from text and send to Home Assistant'
      requestBody:
        description: 'Text command'
        required: true
        content:
          text/plain:
            schema:
              type: string
      parameters:
        - in: query
          name: nohass
          description: 'True if intent should NOT be sent to Home Assistant'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /api/text-to-speech:
    post:
      summary: 'Speak a message using configured text to speech system'
      requestBody:
        description: 'Text to speak'
        required: true
        content:
          text/plain:
            schema:
              type: string
      parameters:
        - in: query
          name: repeat
          description: 'True if Rhasspy should repeat the last spoken sentence'
          schema:
            type: boolean
            default: false
        - in: query
          name: voice
          description: 'Override default voice'
          schema:
            type: string
        - in: query
          name: language
          description: 'Override default language'
          schema:
            type: string
        - in: query
          name: play
          description: 'Speak if true, return WAV data if false'
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/play-wav:
    post:
      summary: 'Play WAV data using configured audio output'
      requestBody:
        description: 'WAV data or URL'
        required: true
        content:
          audio/wav:
            schema:
              type: string
              format: binary
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/speech-to-intent:
    post:
      summary: 'Transcribe WAV data, extract intent, and send to Home Assistant'
      requestBody:
        description: 'WAV data (16-bit 16Khz mono preferred)'
        required: true
        content:
          audio/wav:
            schema:
              type: string
              format: binary
      parameters:
        - in: query
          name: nohass
          description: 'True if intent should NOT be sent to Home Assistant'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /api/start-recording:
    post:
      summary: 'Record WAV file from microphone until stopped'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/stop-recording:
    post:
      summary: 'Stop recording WAV file, transcribe, extract intent, and send to Home Assistant'
      parameters:
        - in: query
          name: nohass
          description: 'True if intent should NOT be sent to Home Assistant'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Intent
          content:
            application/json:
              schema:
                type: object
  /api/download-profile:
    post:
      summary: 'Force Rhasspy to download files for current profile'
      parameters:
        - in: query
          name: delete
          description: 'True if download cache should be deleted'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/slots:
    get:
      summary: 'Get all slot values'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
    post:
      summary: 'Add to or overwrite slot values'
      requestBody:
        description: 'JSON with slot names and value lists'
        required: true
        content:
          application/json:
            schema:
              type: object
      parameters:
        - in: query
          name: overwrite_all
          description: 'True if slots in JSON should be overwritten'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/version:
    get:
      summary: 'Get Rhasspy version'
      produces:
        - text/plain
      responses:
        '200':
          description: Version
          schema:
            type: string
  /api/intents:
    get:
      summary: 'Get all defined intents'
      produces:
        - application/json
      responses:
        '200':
          description: intents
          schema:
            type: object
